version: "3.9"
services:
  
      # pulladstomq:
      #     container_name: PullADsToMQ
      #     image: jah118/poll
      #     restart: unless-stopped
      # environment:
      # - ASPNETCORE_ENVIRONMENT=Development
      # - RABBIT_HOSTNAME=rabbitmq
      # depends_on:
      #   - rabbitmq
      #   -add other services
       routeslipforpads:
           container_name: routeslipForP-Ads
           image: jah118/routeslip_for_p_ads
#           restart: unless-stopped
#           environment:
#            - ASPNETCORE_ENVIRONMENT=Development
#            - redisConn=34534534534534q5q34534q532453

         #   -add other services






